// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1.2 (64-bit)
// Version: 2022.1.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tiled_conv_conv_7x7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Y_buf_0_address0,
        Y_buf_0_ce0,
        Y_buf_0_we0,
        Y_buf_0_d0,
        Y_buf_1_address0,
        Y_buf_1_ce0,
        Y_buf_1_we0,
        Y_buf_1_d0,
        Y_buf_2_address0,
        Y_buf_2_ce0,
        Y_buf_2_we0,
        Y_buf_2_d0,
        Y_buf_3_address0,
        Y_buf_3_ce0,
        Y_buf_3_we0,
        Y_buf_3_d0,
        X_buf_0_address0,
        X_buf_0_ce0,
        X_buf_0_q0,
        X_buf_1_address0,
        X_buf_1_ce0,
        X_buf_1_q0,
        X_buf_2_address0,
        X_buf_2_ce0,
        X_buf_2_q0,
        X_buf_3_address0,
        X_buf_3_ce0,
        X_buf_3_q0,
        X_buf_4_address0,
        X_buf_4_ce0,
        X_buf_4_q0,
        X_buf_5_address0,
        X_buf_5_ce0,
        X_buf_5_q0,
        X_buf_6_address0,
        X_buf_6_ce0,
        X_buf_6_q0,
        X_buf_7_address0,
        X_buf_7_ce0,
        X_buf_7_q0,
        X_buf_8_address0,
        X_buf_8_ce0,
        X_buf_8_q0,
        X_buf_9_address0,
        X_buf_9_ce0,
        X_buf_9_q0,
        X_buf_10_address0,
        X_buf_10_ce0,
        X_buf_10_q0,
        X_buf_11_address0,
        X_buf_11_ce0,
        X_buf_11_q0,
        X_buf_12_address0,
        X_buf_12_ce0,
        X_buf_12_q0,
        X_buf_13_address0,
        X_buf_13_ce0,
        X_buf_13_q0,
        X_buf_14_address0,
        X_buf_14_ce0,
        X_buf_14_q0,
        X_buf_15_address0,
        X_buf_15_ce0,
        X_buf_15_q0,
        X_buf_16_address0,
        X_buf_16_ce0,
        X_buf_16_q0,
        X_buf_17_address0,
        X_buf_17_ce0,
        X_buf_17_q0,
        X_buf_18_address0,
        X_buf_18_ce0,
        X_buf_18_q0,
        X_buf_19_address0,
        X_buf_19_ce0,
        X_buf_19_q0,
        X_buf_20_address0,
        X_buf_20_ce0,
        X_buf_20_q0,
        X_buf_21_address0,
        X_buf_21_ce0,
        X_buf_21_q0,
        X_buf_22_address0,
        X_buf_22_ce0,
        X_buf_22_q0,
        X_buf_23_address0,
        X_buf_23_ce0,
        X_buf_23_q0,
        X_buf_24_address0,
        X_buf_24_ce0,
        X_buf_24_q0,
        X_buf_25_address0,
        X_buf_25_ce0,
        X_buf_25_q0,
        X_buf_26_address0,
        X_buf_26_ce0,
        X_buf_26_q0,
        X_buf_27_address0,
        X_buf_27_ce0,
        X_buf_27_q0,
        X_buf_28_address0,
        X_buf_28_ce0,
        X_buf_28_q0,
        X_buf_29_address0,
        X_buf_29_ce0,
        X_buf_29_q0,
        X_buf_30_address0,
        X_buf_30_ce0,
        X_buf_30_q0,
        X_buf_31_address0,
        X_buf_31_ce0,
        X_buf_31_q0,
        X_buf_32_address0,
        X_buf_32_ce0,
        X_buf_32_q0,
        X_buf_33_address0,
        X_buf_33_ce0,
        X_buf_33_q0,
        X_buf_34_address0,
        X_buf_34_ce0,
        X_buf_34_q0,
        X_buf_35_address0,
        X_buf_35_ce0,
        X_buf_35_q0,
        X_buf_36_address0,
        X_buf_36_ce0,
        X_buf_36_q0,
        X_buf_37_address0,
        X_buf_37_ce0,
        X_buf_37_q0,
        X_buf_38_address0,
        X_buf_38_ce0,
        X_buf_38_q0,
        X_buf_39_address0,
        X_buf_39_ce0,
        X_buf_39_q0,
        X_buf_40_address0,
        X_buf_40_ce0,
        X_buf_40_q0,
        X_buf_41_address0,
        X_buf_41_ce0,
        X_buf_41_q0,
        X_buf_42_address0,
        X_buf_42_ce0,
        X_buf_42_q0,
        X_buf_43_address0,
        X_buf_43_ce0,
        X_buf_43_q0,
        X_buf_44_address0,
        X_buf_44_ce0,
        X_buf_44_q0,
        W_buf_6_address0,
        W_buf_6_ce0,
        W_buf_6_q0,
        W_buf_6_address1,
        W_buf_6_ce1,
        W_buf_6_q1,
        W_buf_6_address2,
        W_buf_6_ce2,
        W_buf_6_q2,
        p_read,
        p_read1,
        p_read2,
        p_read3
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] Y_buf_0_address0;
output   Y_buf_0_ce0;
output   Y_buf_0_we0;
output  [15:0] Y_buf_0_d0;
output  [8:0] Y_buf_1_address0;
output   Y_buf_1_ce0;
output   Y_buf_1_we0;
output  [15:0] Y_buf_1_d0;
output  [8:0] Y_buf_2_address0;
output   Y_buf_2_ce0;
output   Y_buf_2_we0;
output  [15:0] Y_buf_2_d0;
output  [8:0] Y_buf_3_address0;
output   Y_buf_3_ce0;
output   Y_buf_3_we0;
output  [15:0] Y_buf_3_d0;
output  [7:0] X_buf_0_address0;
output   X_buf_0_ce0;
input  [15:0] X_buf_0_q0;
output  [7:0] X_buf_1_address0;
output   X_buf_1_ce0;
input  [15:0] X_buf_1_q0;
output  [7:0] X_buf_2_address0;
output   X_buf_2_ce0;
input  [15:0] X_buf_2_q0;
output  [7:0] X_buf_3_address0;
output   X_buf_3_ce0;
input  [15:0] X_buf_3_q0;
output  [7:0] X_buf_4_address0;
output   X_buf_4_ce0;
input  [15:0] X_buf_4_q0;
output  [7:0] X_buf_5_address0;
output   X_buf_5_ce0;
input  [15:0] X_buf_5_q0;
output  [7:0] X_buf_6_address0;
output   X_buf_6_ce0;
input  [15:0] X_buf_6_q0;
output  [7:0] X_buf_7_address0;
output   X_buf_7_ce0;
input  [15:0] X_buf_7_q0;
output  [7:0] X_buf_8_address0;
output   X_buf_8_ce0;
input  [15:0] X_buf_8_q0;
output  [7:0] X_buf_9_address0;
output   X_buf_9_ce0;
input  [15:0] X_buf_9_q0;
output  [7:0] X_buf_10_address0;
output   X_buf_10_ce0;
input  [15:0] X_buf_10_q0;
output  [7:0] X_buf_11_address0;
output   X_buf_11_ce0;
input  [15:0] X_buf_11_q0;
output  [7:0] X_buf_12_address0;
output   X_buf_12_ce0;
input  [15:0] X_buf_12_q0;
output  [7:0] X_buf_13_address0;
output   X_buf_13_ce0;
input  [15:0] X_buf_13_q0;
output  [7:0] X_buf_14_address0;
output   X_buf_14_ce0;
input  [15:0] X_buf_14_q0;
output  [7:0] X_buf_15_address0;
output   X_buf_15_ce0;
input  [15:0] X_buf_15_q0;
output  [7:0] X_buf_16_address0;
output   X_buf_16_ce0;
input  [15:0] X_buf_16_q0;
output  [7:0] X_buf_17_address0;
output   X_buf_17_ce0;
input  [15:0] X_buf_17_q0;
output  [7:0] X_buf_18_address0;
output   X_buf_18_ce0;
input  [15:0] X_buf_18_q0;
output  [7:0] X_buf_19_address0;
output   X_buf_19_ce0;
input  [15:0] X_buf_19_q0;
output  [7:0] X_buf_20_address0;
output   X_buf_20_ce0;
input  [15:0] X_buf_20_q0;
output  [7:0] X_buf_21_address0;
output   X_buf_21_ce0;
input  [15:0] X_buf_21_q0;
output  [7:0] X_buf_22_address0;
output   X_buf_22_ce0;
input  [15:0] X_buf_22_q0;
output  [7:0] X_buf_23_address0;
output   X_buf_23_ce0;
input  [15:0] X_buf_23_q0;
output  [7:0] X_buf_24_address0;
output   X_buf_24_ce0;
input  [15:0] X_buf_24_q0;
output  [7:0] X_buf_25_address0;
output   X_buf_25_ce0;
input  [15:0] X_buf_25_q0;
output  [7:0] X_buf_26_address0;
output   X_buf_26_ce0;
input  [15:0] X_buf_26_q0;
output  [7:0] X_buf_27_address0;
output   X_buf_27_ce0;
input  [15:0] X_buf_27_q0;
output  [7:0] X_buf_28_address0;
output   X_buf_28_ce0;
input  [15:0] X_buf_28_q0;
output  [7:0] X_buf_29_address0;
output   X_buf_29_ce0;
input  [15:0] X_buf_29_q0;
output  [7:0] X_buf_30_address0;
output   X_buf_30_ce0;
input  [15:0] X_buf_30_q0;
output  [7:0] X_buf_31_address0;
output   X_buf_31_ce0;
input  [15:0] X_buf_31_q0;
output  [7:0] X_buf_32_address0;
output   X_buf_32_ce0;
input  [15:0] X_buf_32_q0;
output  [7:0] X_buf_33_address0;
output   X_buf_33_ce0;
input  [15:0] X_buf_33_q0;
output  [7:0] X_buf_34_address0;
output   X_buf_34_ce0;
input  [15:0] X_buf_34_q0;
output  [7:0] X_buf_35_address0;
output   X_buf_35_ce0;
input  [15:0] X_buf_35_q0;
output  [7:0] X_buf_36_address0;
output   X_buf_36_ce0;
input  [15:0] X_buf_36_q0;
output  [7:0] X_buf_37_address0;
output   X_buf_37_ce0;
input  [15:0] X_buf_37_q0;
output  [7:0] X_buf_38_address0;
output   X_buf_38_ce0;
input  [15:0] X_buf_38_q0;
output  [7:0] X_buf_39_address0;
output   X_buf_39_ce0;
input  [15:0] X_buf_39_q0;
output  [7:0] X_buf_40_address0;
output   X_buf_40_ce0;
input  [15:0] X_buf_40_q0;
output  [7:0] X_buf_41_address0;
output   X_buf_41_ce0;
input  [15:0] X_buf_41_q0;
output  [7:0] X_buf_42_address0;
output   X_buf_42_ce0;
input  [15:0] X_buf_42_q0;
output  [7:0] X_buf_43_address0;
output   X_buf_43_ce0;
input  [15:0] X_buf_43_q0;
output  [7:0] X_buf_44_address0;
output   X_buf_44_ce0;
input  [15:0] X_buf_44_q0;
output  [6:0] W_buf_6_address0;
output   W_buf_6_ce0;
input  [15:0] W_buf_6_q0;
output  [6:0] W_buf_6_address1;
output   W_buf_6_ce1;
input  [15:0] W_buf_6_q1;
output  [6:0] W_buf_6_address2;
output   W_buf_6_ce2;
input  [15:0] W_buf_6_q2;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;

reg ap_idle;
reg[8:0] Y_buf_0_address0;
reg Y_buf_0_ce0;
reg Y_buf_0_we0;
reg[15:0] Y_buf_0_d0;
reg[8:0] Y_buf_1_address0;
reg Y_buf_1_ce0;
reg Y_buf_1_we0;
reg[15:0] Y_buf_1_d0;
reg[8:0] Y_buf_2_address0;
reg Y_buf_2_ce0;
reg Y_buf_2_we0;
reg[15:0] Y_buf_2_d0;
reg[8:0] Y_buf_3_address0;
reg Y_buf_3_ce0;
reg Y_buf_3_we0;
reg[15:0] Y_buf_3_d0;
reg X_buf_0_ce0;
reg X_buf_1_ce0;
reg X_buf_2_ce0;
reg X_buf_3_ce0;
reg X_buf_4_ce0;
reg X_buf_5_ce0;
reg X_buf_6_ce0;
reg X_buf_7_ce0;
reg X_buf_8_ce0;
reg X_buf_9_ce0;
reg X_buf_10_ce0;
reg X_buf_11_ce0;
reg X_buf_12_ce0;
reg X_buf_13_ce0;
reg X_buf_14_ce0;
reg X_buf_15_ce0;
reg X_buf_16_ce0;
reg X_buf_17_ce0;
reg X_buf_18_ce0;
reg X_buf_19_ce0;
reg X_buf_20_ce0;
reg X_buf_21_ce0;
reg X_buf_22_ce0;
reg X_buf_23_ce0;
reg X_buf_24_ce0;
reg X_buf_25_ce0;
reg X_buf_26_ce0;
reg X_buf_27_ce0;
reg X_buf_28_ce0;
reg X_buf_29_ce0;
reg X_buf_30_ce0;
reg X_buf_31_ce0;
reg X_buf_32_ce0;
reg X_buf_33_ce0;
reg X_buf_34_ce0;
reg X_buf_35_ce0;
reg X_buf_36_ce0;
reg X_buf_37_ce0;
reg X_buf_38_ce0;
reg X_buf_39_ce0;
reg X_buf_40_ce0;
reg X_buf_41_ce0;
reg X_buf_42_ce0;
reg X_buf_43_ce0;
reg X_buf_44_ce0;
reg[6:0] W_buf_6_address0;
reg W_buf_6_ce0;
reg[6:0] W_buf_6_address1;
reg W_buf_6_ce1;
reg[6:0] W_buf_6_address2;
reg W_buf_6_ce2;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state6_pp0_stage2_iter1;
wire    ap_block_state9_pp0_stage2_iter2;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln41_reg_2283;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg  signed [15:0] reg_985;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
wire    ap_block_state8_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
reg  signed [15:0] reg_990;
reg  signed [15:0] reg_994;
wire   [0:0] icmp_ln41_fu_1036_p2;
wire   [10:0] add_ln41_1_fu_1042_p2;
reg   [10:0] add_ln41_1_reg_2287;
wire   [0:0] icmp_ln44_fu_1051_p2;
reg   [0:0] icmp_ln44_reg_2292;
reg   [0:0] icmp_ln44_reg_2292_pp0_iter1_reg;
wire   [0:0] and_ln41_fu_1069_p2;
reg   [0:0] and_ln41_reg_2302;
reg   [0:0] and_ln41_reg_2302_pp0_iter1_reg;
wire   [2:0] select_ln44_fu_1081_p3;
reg   [2:0] select_ln44_reg_2308;
wire   [6:0] mul_ln1319_fu_1093_p2;
reg   [6:0] mul_ln1319_reg_2313;
wire   [1:0] trunc_ln51_fu_1099_p1;
reg   [1:0] trunc_ln51_reg_2324;
reg   [1:0] trunc_ln51_reg_2324_pp0_iter1_reg;
reg   [1:0] trunc_ln51_reg_2324_pp0_iter2_reg;
wire  signed [15:0] rhs_fu_1103_p6;
reg  signed [15:0] rhs_reg_2328;
reg  signed [15:0] rhs_reg_2328_pp0_iter1_reg;
reg  signed [15:0] rhs_reg_2328_pp0_iter2_reg;
reg   [5:0] h_load_reg_2334;
wire   [5:0] select_ln41_1_fu_1123_p3;
reg   [5:0] select_ln41_1_reg_2340;
wire   [15:0] tmp_fu_1273_p41;
reg  signed [15:0] tmp_reg_2601;
wire   [15:0] tmp_1_fu_1357_p41;
reg  signed [15:0] tmp_1_reg_2606;
wire   [15:0] tmp_2_fu_1441_p41;
reg  signed [15:0] tmp_2_reg_2611;
wire   [15:0] tmp_3_fu_1525_p41;
reg  signed [15:0] tmp_3_reg_2616;
wire   [15:0] tmp_4_fu_1609_p41;
reg  signed [15:0] tmp_4_reg_2621;
wire   [15:0] tmp_5_fu_1693_p41;
reg  signed [15:0] tmp_5_reg_2626;
wire   [15:0] tmp_6_fu_1777_p41;
reg  signed [15:0] tmp_6_reg_2631;
wire  signed [28:0] mul_ln864_fu_2192_p2;
reg  signed [28:0] mul_ln864_reg_2641;
wire  signed [28:0] mul_ln864_1_fu_2198_p2;
reg  signed [28:0] mul_ln864_1_reg_2646;
wire  signed [28:0] mul_ln864_2_fu_2204_p2;
reg  signed [28:0] mul_ln864_2_reg_2651;
reg   [15:0] trunc_ln3_reg_2656;
reg   [15:0] trunc_ln864_1_reg_2661;
reg   [15:0] trunc_ln864_2_reg_2666;
wire  signed [27:0] mul_ln1317_fu_2210_p2;
reg  signed [27:0] mul_ln1317_reg_2671;
wire  signed [28:0] mul_ln864_4_fu_2216_p2;
reg  signed [28:0] mul_ln864_4_reg_2676;
wire  signed [28:0] mul_ln864_5_fu_2222_p2;
reg  signed [28:0] mul_ln864_5_reg_2681;
wire   [4:0] select_ln41_2_fu_2012_p3;
reg   [4:0] select_ln41_2_reg_2686;
wire   [4:0] select_ln44_1_fu_2025_p3;
reg   [4:0] select_ln44_1_reg_2692;
wire  signed [28:0] mul_ln864_3_fu_2228_p2;
reg  signed [28:0] mul_ln864_3_reg_2697;
wire   [15:0] add_ln859_fu_2074_p2;
reg   [15:0] add_ln859_reg_2702;
wire   [15:0] add_ln859_4_fu_2089_p2;
reg   [15:0] add_ln859_4_reg_2707;
reg   [8:0] Y_buf_0_addr_reg_2712;
reg   [8:0] Y_buf_1_addr_reg_2717;
reg   [8:0] Y_buf_2_addr_reg_2722;
reg   [8:0] Y_buf_3_addr_reg_2727;
wire   [16:0] sub_ln1466_fu_2173_p2;
reg   [16:0] sub_ln1466_reg_2732;
wire   [15:0] add_ln859_6_fu_2179_p2;
reg   [15:0] add_ln859_6_reg_2737;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln1317_fu_1153_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln1319_1_fu_1207_p1;
wire   [63:0] zext_ln1319_2_fu_1217_p1;
wire   [63:0] zext_ln1319_3_fu_1227_p1;
wire   [63:0] zext_ln1319_4_fu_1248_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln1319_6_fu_1258_p1;
wire   [63:0] zext_ln1319_7_fu_1268_p1;
wire   [63:0] zext_ln1319_5_fu_1914_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] p_cast_fu_2138_p1;
reg   [2:0] kernel_fu_220;
wire   [2:0] add_ln47_fu_1861_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_kernel_load;
reg   [5:0] w_fu_224;
wire   [5:0] select_ln44_2_fu_1237_p3;
reg   [4:0] ow_fu_228;
reg   [7:0] indvar_flatten_fu_232;
wire   [7:0] select_ln44_3_fu_1872_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load_3;
reg   [7:0] grp_load_fu_982_p1;
reg   [5:0] h_fu_236;
wire   [5:0] select_ln41_5_fu_1903_p3;
reg   [4:0] oh_fu_240;
reg   [10:0] indvar_flatten71_fu_244;
reg   [10:0] ap_sig_allocacmp_indvar_flatten71_load;
wire  signed [15:0] lhs_fu_2160_p2;
wire   [0:0] icmp_ln1466_fu_2187_p2;
wire   [0:0] icmp_ln47_fu_1063_p2;
wire   [0:0] xor_ln41_fu_1057_p2;
wire   [0:0] or_ln44_fu_1075_p2;
wire   [2:0] mul_ln1319_fu_1093_p0;
wire   [5:0] mul_ln1319_fu_1093_p1;
wire   [5:0] select_ln41_4_fu_1130_p3;
wire   [5:0] add_ln41_2_fu_1137_p2;
wire   [7:0] zext_ln41_fu_1143_p1;
wire   [7:0] add_ln41_3_fu_1147_p2;
wire   [6:0] add_ln1319_fu_1202_p2;
wire   [6:0] add_ln1319_1_fu_1212_p2;
wire   [6:0] add_ln1319_2_fu_1222_p2;
wire   [5:0] indvars_iv_next295_fu_1232_p2;
wire   [6:0] add_ln1319_3_fu_1243_p2;
wire   [6:0] add_ln1319_5_fu_1253_p2;
wire   [6:0] add_ln1319_6_fu_1263_p2;
wire   [7:0] add_ln44_1_fu_1866_p2;
wire   [5:0] indvars_iv_next305_fu_1898_p2;
wire   [6:0] add_ln1319_4_fu_1909_p2;
wire   [4:0] add_ln41_fu_1999_p2;
wire   [4:0] select_ln41_fu_2005_p3;
wire   [4:0] add_ln44_fu_2019_p2;
wire   [14:0] tmp_8_fu_2057_p4;
wire   [15:0] trunc_ln864_4_fu_2039_p4;
wire   [15:0] factor_fu_2066_p3;
wire   [15:0] trunc_ln864_5_fu_2048_p4;
wire   [15:0] add_ln859_3_fu_2084_p2;
wire   [15:0] add_ln859_2_fu_2080_p2;
wire   [6:0] tmp_7_fu_2112_p3;
wire   [8:0] tmp_s_fu_2105_p3;
wire   [8:0] tmp_11_cast_fu_2119_p1;
wire   [8:0] empty_66_fu_2123_p2;
wire   [8:0] select_ln44_1_cast_fu_2129_p1;
wire   [8:0] empty_67_fu_2132_p2;
wire   [15:0] trunc_ln864_3_fu_2146_p4;
wire   [15:0] add_ln859_1_fu_2155_p2;
wire  signed [16:0] sext_ln859_fu_2169_p1;
wire  signed [16:0] sext_ln859_1_fu_2184_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [6:0] mul_ln1319_fu_1093_p00;
reg    ap_condition_1455;
reg    ap_condition_1460;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

tiled_conv_mul_3ns_6ns_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 7 ))
mul_3ns_6ns_7_1_1_U201(
    .din0(mul_ln1319_fu_1093_p0),
    .din1(mul_ln1319_fu_1093_p1),
    .dout(mul_ln1319_fu_1093_p2)
);

tiled_conv_mux_43_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
mux_43_16_1_1_U202(
    .din0(p_read),
    .din1(p_read1),
    .din2(p_read2),
    .din3(p_read3),
    .din4(select_ln44_fu_1081_p3),
    .dout(rhs_fu_1103_p6)
);

tiled_conv_mux_396_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mux_396_16_1_1_U203(
    .din0(X_buf_0_q0),
    .din1(16'd0),
    .din2(X_buf_2_q0),
    .din3(16'd0),
    .din4(X_buf_4_q0),
    .din5(16'd0),
    .din6(X_buf_6_q0),
    .din7(16'd0),
    .din8(X_buf_8_q0),
    .din9(16'd0),
    .din10(X_buf_10_q0),
    .din11(16'd0),
    .din12(X_buf_12_q0),
    .din13(16'd0),
    .din14(X_buf_14_q0),
    .din15(16'd0),
    .din16(X_buf_16_q0),
    .din17(16'd0),
    .din18(X_buf_18_q0),
    .din19(16'd0),
    .din20(X_buf_20_q0),
    .din21(16'd0),
    .din22(X_buf_22_q0),
    .din23(16'd0),
    .din24(X_buf_24_q0),
    .din25(16'd0),
    .din26(X_buf_26_q0),
    .din27(16'd0),
    .din28(X_buf_28_q0),
    .din29(16'd0),
    .din30(X_buf_30_q0),
    .din31(16'd0),
    .din32(X_buf_32_q0),
    .din33(16'd0),
    .din34(X_buf_34_q0),
    .din35(16'd0),
    .din36(X_buf_36_q0),
    .din37(16'd0),
    .din38(X_buf_38_q0),
    .din39(select_ln44_2_fu_1237_p3),
    .dout(tmp_fu_1273_p41)
);

tiled_conv_mux_396_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mux_396_16_1_1_U204(
    .din0(X_buf_1_q0),
    .din1(16'd0),
    .din2(X_buf_3_q0),
    .din3(16'd0),
    .din4(X_buf_5_q0),
    .din5(16'd0),
    .din6(X_buf_7_q0),
    .din7(16'd0),
    .din8(X_buf_9_q0),
    .din9(16'd0),
    .din10(X_buf_11_q0),
    .din11(16'd0),
    .din12(X_buf_13_q0),
    .din13(16'd0),
    .din14(X_buf_15_q0),
    .din15(16'd0),
    .din16(X_buf_17_q0),
    .din17(16'd0),
    .din18(X_buf_19_q0),
    .din19(16'd0),
    .din20(X_buf_21_q0),
    .din21(16'd0),
    .din22(X_buf_23_q0),
    .din23(16'd0),
    .din24(X_buf_25_q0),
    .din25(16'd0),
    .din26(X_buf_27_q0),
    .din27(16'd0),
    .din28(X_buf_29_q0),
    .din29(16'd0),
    .din30(X_buf_31_q0),
    .din31(16'd0),
    .din32(X_buf_33_q0),
    .din33(16'd0),
    .din34(X_buf_35_q0),
    .din35(16'd0),
    .din36(X_buf_37_q0),
    .din37(16'd0),
    .din38(X_buf_39_q0),
    .din39(select_ln44_2_fu_1237_p3),
    .dout(tmp_1_fu_1357_p41)
);

tiled_conv_mux_396_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mux_396_16_1_1_U205(
    .din0(X_buf_2_q0),
    .din1(16'd0),
    .din2(X_buf_4_q0),
    .din3(16'd0),
    .din4(X_buf_6_q0),
    .din5(16'd0),
    .din6(X_buf_8_q0),
    .din7(16'd0),
    .din8(X_buf_10_q0),
    .din9(16'd0),
    .din10(X_buf_12_q0),
    .din11(16'd0),
    .din12(X_buf_14_q0),
    .din13(16'd0),
    .din14(X_buf_16_q0),
    .din15(16'd0),
    .din16(X_buf_18_q0),
    .din17(16'd0),
    .din18(X_buf_20_q0),
    .din19(16'd0),
    .din20(X_buf_22_q0),
    .din21(16'd0),
    .din22(X_buf_24_q0),
    .din23(16'd0),
    .din24(X_buf_26_q0),
    .din25(16'd0),
    .din26(X_buf_28_q0),
    .din27(16'd0),
    .din28(X_buf_30_q0),
    .din29(16'd0),
    .din30(X_buf_32_q0),
    .din31(16'd0),
    .din32(X_buf_34_q0),
    .din33(16'd0),
    .din34(X_buf_36_q0),
    .din35(16'd0),
    .din36(X_buf_38_q0),
    .din37(16'd0),
    .din38(X_buf_40_q0),
    .din39(select_ln44_2_fu_1237_p3),
    .dout(tmp_2_fu_1441_p41)
);

tiled_conv_mux_396_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mux_396_16_1_1_U206(
    .din0(X_buf_3_q0),
    .din1(16'd0),
    .din2(X_buf_5_q0),
    .din3(16'd0),
    .din4(X_buf_7_q0),
    .din5(16'd0),
    .din6(X_buf_9_q0),
    .din7(16'd0),
    .din8(X_buf_11_q0),
    .din9(16'd0),
    .din10(X_buf_13_q0),
    .din11(16'd0),
    .din12(X_buf_15_q0),
    .din13(16'd0),
    .din14(X_buf_17_q0),
    .din15(16'd0),
    .din16(X_buf_19_q0),
    .din17(16'd0),
    .din18(X_buf_21_q0),
    .din19(16'd0),
    .din20(X_buf_23_q0),
    .din21(16'd0),
    .din22(X_buf_25_q0),
    .din23(16'd0),
    .din24(X_buf_27_q0),
    .din25(16'd0),
    .din26(X_buf_29_q0),
    .din27(16'd0),
    .din28(X_buf_31_q0),
    .din29(16'd0),
    .din30(X_buf_33_q0),
    .din31(16'd0),
    .din32(X_buf_35_q0),
    .din33(16'd0),
    .din34(X_buf_37_q0),
    .din35(16'd0),
    .din36(X_buf_39_q0),
    .din37(16'd0),
    .din38(X_buf_41_q0),
    .din39(select_ln44_2_fu_1237_p3),
    .dout(tmp_3_fu_1525_p41)
);

tiled_conv_mux_396_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mux_396_16_1_1_U207(
    .din0(X_buf_4_q0),
    .din1(16'd0),
    .din2(X_buf_6_q0),
    .din3(16'd0),
    .din4(X_buf_8_q0),
    .din5(16'd0),
    .din6(X_buf_10_q0),
    .din7(16'd0),
    .din8(X_buf_12_q0),
    .din9(16'd0),
    .din10(X_buf_14_q0),
    .din11(16'd0),
    .din12(X_buf_16_q0),
    .din13(16'd0),
    .din14(X_buf_18_q0),
    .din15(16'd0),
    .din16(X_buf_20_q0),
    .din17(16'd0),
    .din18(X_buf_22_q0),
    .din19(16'd0),
    .din20(X_buf_24_q0),
    .din21(16'd0),
    .din22(X_buf_26_q0),
    .din23(16'd0),
    .din24(X_buf_28_q0),
    .din25(16'd0),
    .din26(X_buf_30_q0),
    .din27(16'd0),
    .din28(X_buf_32_q0),
    .din29(16'd0),
    .din30(X_buf_34_q0),
    .din31(16'd0),
    .din32(X_buf_36_q0),
    .din33(16'd0),
    .din34(X_buf_38_q0),
    .din35(16'd0),
    .din36(X_buf_40_q0),
    .din37(16'd0),
    .din38(X_buf_42_q0),
    .din39(select_ln44_2_fu_1237_p3),
    .dout(tmp_4_fu_1609_p41)
);

tiled_conv_mux_396_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mux_396_16_1_1_U208(
    .din0(X_buf_5_q0),
    .din1(16'd0),
    .din2(X_buf_7_q0),
    .din3(16'd0),
    .din4(X_buf_9_q0),
    .din5(16'd0),
    .din6(X_buf_11_q0),
    .din7(16'd0),
    .din8(X_buf_13_q0),
    .din9(16'd0),
    .din10(X_buf_15_q0),
    .din11(16'd0),
    .din12(X_buf_17_q0),
    .din13(16'd0),
    .din14(X_buf_19_q0),
    .din15(16'd0),
    .din16(X_buf_21_q0),
    .din17(16'd0),
    .din18(X_buf_23_q0),
    .din19(16'd0),
    .din20(X_buf_25_q0),
    .din21(16'd0),
    .din22(X_buf_27_q0),
    .din23(16'd0),
    .din24(X_buf_29_q0),
    .din25(16'd0),
    .din26(X_buf_31_q0),
    .din27(16'd0),
    .din28(X_buf_33_q0),
    .din29(16'd0),
    .din30(X_buf_35_q0),
    .din31(16'd0),
    .din32(X_buf_37_q0),
    .din33(16'd0),
    .din34(X_buf_39_q0),
    .din35(16'd0),
    .din36(X_buf_41_q0),
    .din37(16'd0),
    .din38(X_buf_43_q0),
    .din39(select_ln44_2_fu_1237_p3),
    .dout(tmp_5_fu_1693_p41)
);

tiled_conv_mux_396_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mux_396_16_1_1_U209(
    .din0(X_buf_6_q0),
    .din1(16'd0),
    .din2(X_buf_8_q0),
    .din3(16'd0),
    .din4(X_buf_10_q0),
    .din5(16'd0),
    .din6(X_buf_12_q0),
    .din7(16'd0),
    .din8(X_buf_14_q0),
    .din9(16'd0),
    .din10(X_buf_16_q0),
    .din11(16'd0),
    .din12(X_buf_18_q0),
    .din13(16'd0),
    .din14(X_buf_20_q0),
    .din15(16'd0),
    .din16(X_buf_22_q0),
    .din17(16'd0),
    .din18(X_buf_24_q0),
    .din19(16'd0),
    .din20(X_buf_26_q0),
    .din21(16'd0),
    .din22(X_buf_28_q0),
    .din23(16'd0),
    .din24(X_buf_30_q0),
    .din25(16'd0),
    .din26(X_buf_32_q0),
    .din27(16'd0),
    .din28(X_buf_34_q0),
    .din29(16'd0),
    .din30(X_buf_36_q0),
    .din31(16'd0),
    .din32(X_buf_38_q0),
    .din33(16'd0),
    .din34(X_buf_40_q0),
    .din35(16'd0),
    .din36(X_buf_42_q0),
    .din37(16'd0),
    .din38(X_buf_44_q0),
    .din39(select_ln44_2_fu_1237_p3),
    .dout(tmp_6_fu_1777_p41)
);

tiled_conv_mul_mul_16s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_mul_16s_16s_29_1_1_U210(
    .din0(reg_985),
    .din1(tmp_reg_2601),
    .dout(mul_ln864_fu_2192_p2)
);

tiled_conv_mul_mul_16s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_mul_16s_16s_29_1_1_U211(
    .din0(reg_990),
    .din1(tmp_1_reg_2606),
    .dout(mul_ln864_1_fu_2198_p2)
);

tiled_conv_mul_mul_16s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_mul_16s_16s_29_1_1_U212(
    .din0(reg_994),
    .din1(tmp_2_reg_2611),
    .dout(mul_ln864_2_fu_2204_p2)
);

tiled_conv_mul_mul_16s_16s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_mul_16s_16s_28_1_1_U213(
    .din0(reg_985),
    .din1(tmp_3_reg_2616),
    .dout(mul_ln1317_fu_2210_p2)
);

tiled_conv_mul_mul_16s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_mul_16s_16s_29_1_1_U214(
    .din0(reg_990),
    .din1(tmp_5_reg_2626),
    .dout(mul_ln864_4_fu_2216_p2)
);

tiled_conv_mul_mul_16s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_mul_16s_16s_29_1_1_U215(
    .din0(reg_994),
    .din1(tmp_6_reg_2631),
    .dout(mul_ln864_5_fu_2222_p2)
);

tiled_conv_mul_mul_16s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_mul_16s_16s_29_1_1_U216(
    .din0(reg_985),
    .din1(tmp_4_reg_2621),
    .dout(mul_ln864_3_fu_2228_p2)
);

tiled_conv_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            h_fu_236 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            h_fu_236 <= select_ln41_5_fu_1903_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten71_fu_244 <= 11'd0;
    end else if (((icmp_ln41_reg_2283 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten71_fu_244 <= add_ln41_1_reg_2287;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_fu_232 <= 8'd0;
    end else if (((icmp_ln41_reg_2283 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten_fu_232 <= select_ln44_3_fu_1872_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_fu_220 <= 3'd0;
    end else if (((icmp_ln41_reg_2283 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        kernel_fu_220 <= add_ln47_fu_1861_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        oh_fu_240 <= 5'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        oh_fu_240 <= select_ln41_2_fu_2012_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ow_fu_228 <= 5'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ow_fu_228 <= select_ln44_1_fu_2025_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reg_985 <= W_buf_6_q0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln41_reg_2283 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_985 <= W_buf_6_q2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_fu_224 <= 6'd0;
    end else if (((icmp_ln41_reg_2283 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        w_fu_224 <= select_ln44_2_fu_1237_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Y_buf_0_addr_reg_2712 <= p_cast_fu_2138_p1;
        Y_buf_1_addr_reg_2717 <= p_cast_fu_2138_p1;
        Y_buf_2_addr_reg_2722 <= p_cast_fu_2138_p1;
        Y_buf_3_addr_reg_2727 <= p_cast_fu_2138_p1;
        add_ln41_1_reg_2287 <= add_ln41_1_fu_1042_p2;
        add_ln859_6_reg_2737 <= add_ln859_6_fu_2179_p2;
        and_ln41_reg_2302_pp0_iter1_reg <= and_ln41_reg_2302;
        icmp_ln41_reg_2283 <= icmp_ln41_fu_1036_p2;
        icmp_ln44_reg_2292_pp0_iter1_reg <= icmp_ln44_reg_2292;
        mul_ln864_1_reg_2646 <= mul_ln864_1_fu_2198_p2;
        mul_ln864_2_reg_2651 <= mul_ln864_2_fu_2204_p2;
        mul_ln864_reg_2641 <= mul_ln864_fu_2192_p2;
        rhs_reg_2328_pp0_iter1_reg <= rhs_reg_2328;
        rhs_reg_2328_pp0_iter2_reg <= rhs_reg_2328_pp0_iter1_reg;
        sub_ln1466_reg_2732 <= sub_ln1466_fu_2173_p2;
        trunc_ln51_reg_2324_pp0_iter1_reg <= trunc_ln51_reg_2324;
        trunc_ln51_reg_2324_pp0_iter2_reg <= trunc_ln51_reg_2324_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln859_4_reg_2707 <= add_ln859_4_fu_2089_p2;
        add_ln859_reg_2702 <= add_ln859_fu_2074_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        mul_ln864_3_reg_2697 <= mul_ln864_3_fu_2228_p2;
        select_ln41_2_reg_2686 <= select_ln41_2_fu_2012_p3;
        select_ln44_1_reg_2692 <= select_ln44_1_fu_2025_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_1036_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln41_reg_2302 <= and_ln41_fu_1069_p2;
        icmp_ln44_reg_2292 <= icmp_ln44_fu_1051_p2;
        mul_ln1319_reg_2313 <= mul_ln1319_fu_1093_p2;
        rhs_reg_2328 <= rhs_fu_1103_p6;
        select_ln44_reg_2308 <= select_ln44_fu_1081_p3;
        trunc_ln51_reg_2324 <= trunc_ln51_fu_1099_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_reg_2283 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        h_load_reg_2334 <= h_fu_236;
        select_ln41_1_reg_2340 <= select_ln41_1_fu_1123_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_ln1317_reg_2671 <= mul_ln1317_fu_2210_p2;
        mul_ln864_4_reg_2676 <= mul_ln864_4_fu_2216_p2;
        mul_ln864_5_reg_2681 <= mul_ln864_5_fu_2222_p2;
        trunc_ln3_reg_2656 <= {{mul_ln864_reg_2641[28:13]}};
        trunc_ln864_1_reg_2661 <= {{mul_ln864_1_reg_2646[28:13]}};
        trunc_ln864_2_reg_2666 <= {{mul_ln864_2_reg_2651[28:13]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln41_reg_2283 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_990 <= W_buf_6_q1;
        reg_994 <= W_buf_6_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_reg_2283 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_1_reg_2606 <= tmp_1_fu_1357_p41;
        tmp_2_reg_2611 <= tmp_2_fu_1441_p41;
        tmp_3_reg_2616 <= tmp_3_fu_1525_p41;
        tmp_4_reg_2621 <= tmp_4_fu_1609_p41;
        tmp_5_reg_2626 <= tmp_5_fu_1693_p41;
        tmp_6_reg_2631 <= tmp_6_fu_1777_p41;
        tmp_reg_2601 <= tmp_fu_1273_p41;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_buf_6_address0 = zext_ln1319_5_fu_1914_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        W_buf_6_address0 = zext_ln1319_7_fu_1268_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        W_buf_6_address0 = zext_ln1319_3_fu_1227_p1;
    end else begin
        W_buf_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            W_buf_6_address1 = zext_ln1319_6_fu_1258_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            W_buf_6_address1 = zext_ln1319_2_fu_1217_p1;
        end else begin
            W_buf_6_address1 = 'bx;
        end
    end else begin
        W_buf_6_address1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            W_buf_6_address2 = zext_ln1319_4_fu_1248_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            W_buf_6_address2 = zext_ln1319_1_fu_1207_p1;
        end else begin
            W_buf_6_address2 = 'bx;
        end
    end else begin
        W_buf_6_address2 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        W_buf_6_ce0 = 1'b1;
    end else begin
        W_buf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        W_buf_6_ce1 = 1'b1;
    end else begin
        W_buf_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        W_buf_6_ce2 = 1'b1;
    end else begin
        W_buf_6_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_0_ce0 = 1'b1;
    end else begin
        X_buf_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_10_ce0 = 1'b1;
    end else begin
        X_buf_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_11_ce0 = 1'b1;
    end else begin
        X_buf_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_12_ce0 = 1'b1;
    end else begin
        X_buf_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_13_ce0 = 1'b1;
    end else begin
        X_buf_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_14_ce0 = 1'b1;
    end else begin
        X_buf_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_15_ce0 = 1'b1;
    end else begin
        X_buf_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_16_ce0 = 1'b1;
    end else begin
        X_buf_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_17_ce0 = 1'b1;
    end else begin
        X_buf_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_18_ce0 = 1'b1;
    end else begin
        X_buf_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_19_ce0 = 1'b1;
    end else begin
        X_buf_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_1_ce0 = 1'b1;
    end else begin
        X_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_20_ce0 = 1'b1;
    end else begin
        X_buf_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_21_ce0 = 1'b1;
    end else begin
        X_buf_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_22_ce0 = 1'b1;
    end else begin
        X_buf_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_23_ce0 = 1'b1;
    end else begin
        X_buf_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_24_ce0 = 1'b1;
    end else begin
        X_buf_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_25_ce0 = 1'b1;
    end else begin
        X_buf_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_26_ce0 = 1'b1;
    end else begin
        X_buf_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_27_ce0 = 1'b1;
    end else begin
        X_buf_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_28_ce0 = 1'b1;
    end else begin
        X_buf_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_29_ce0 = 1'b1;
    end else begin
        X_buf_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_2_ce0 = 1'b1;
    end else begin
        X_buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_30_ce0 = 1'b1;
    end else begin
        X_buf_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_31_ce0 = 1'b1;
    end else begin
        X_buf_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_32_ce0 = 1'b1;
    end else begin
        X_buf_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_33_ce0 = 1'b1;
    end else begin
        X_buf_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_34_ce0 = 1'b1;
    end else begin
        X_buf_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_35_ce0 = 1'b1;
    end else begin
        X_buf_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_36_ce0 = 1'b1;
    end else begin
        X_buf_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_37_ce0 = 1'b1;
    end else begin
        X_buf_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_38_ce0 = 1'b1;
    end else begin
        X_buf_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_39_ce0 = 1'b1;
    end else begin
        X_buf_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_3_ce0 = 1'b1;
    end else begin
        X_buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_40_ce0 = 1'b1;
    end else begin
        X_buf_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_41_ce0 = 1'b1;
    end else begin
        X_buf_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_42_ce0 = 1'b1;
    end else begin
        X_buf_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_43_ce0 = 1'b1;
    end else begin
        X_buf_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_44_ce0 = 1'b1;
    end else begin
        X_buf_44_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_4_ce0 = 1'b1;
    end else begin
        X_buf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_5_ce0 = 1'b1;
    end else begin
        X_buf_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_6_ce0 = 1'b1;
    end else begin
        X_buf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_7_ce0 = 1'b1;
    end else begin
        X_buf_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_8_ce0 = 1'b1;
    end else begin
        X_buf_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_buf_9_ce0 = 1'b1;
    end else begin
        X_buf_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        Y_buf_0_address0 = Y_buf_0_addr_reg_2712;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Y_buf_0_address0 = p_cast_fu_2138_p1;
    end else begin
        Y_buf_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Y_buf_0_ce0 = 1'b1;
    end else begin
        Y_buf_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            Y_buf_0_d0 = add_ln859_6_reg_2737;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            Y_buf_0_d0 = 16'd0;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Y_buf_0_d0 = lhs_fu_2160_p2;
        end else begin
            Y_buf_0_d0 = 'bx;
        end
    end else begin
        Y_buf_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1466_fu_2187_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln51_reg_2324_pp0_iter2_reg == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln51_reg_2324_pp0_iter1_reg == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (trunc_ln51_reg_2324_pp0_iter2_reg == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Y_buf_0_we0 = 1'b1;
    end else begin
        Y_buf_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        Y_buf_1_address0 = Y_buf_1_addr_reg_2717;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Y_buf_1_address0 = p_cast_fu_2138_p1;
    end else begin
        Y_buf_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Y_buf_1_ce0 = 1'b1;
    end else begin
        Y_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            Y_buf_1_d0 = add_ln859_6_reg_2737;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            Y_buf_1_d0 = 16'd0;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Y_buf_1_d0 = lhs_fu_2160_p2;
        end else begin
            Y_buf_1_d0 = 'bx;
        end
    end else begin
        Y_buf_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1466_fu_2187_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln51_reg_2324_pp0_iter2_reg == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln51_reg_2324_pp0_iter1_reg == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (trunc_ln51_reg_2324_pp0_iter2_reg == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Y_buf_1_we0 = 1'b1;
    end else begin
        Y_buf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        Y_buf_2_address0 = Y_buf_2_addr_reg_2722;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Y_buf_2_address0 = p_cast_fu_2138_p1;
    end else begin
        Y_buf_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Y_buf_2_ce0 = 1'b1;
    end else begin
        Y_buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            Y_buf_2_d0 = add_ln859_6_reg_2737;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            Y_buf_2_d0 = 16'd0;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Y_buf_2_d0 = lhs_fu_2160_p2;
        end else begin
            Y_buf_2_d0 = 'bx;
        end
    end else begin
        Y_buf_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1466_fu_2187_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln51_reg_2324_pp0_iter2_reg == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln51_reg_2324_pp0_iter1_reg == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (trunc_ln51_reg_2324_pp0_iter2_reg == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Y_buf_2_we0 = 1'b1;
    end else begin
        Y_buf_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        Y_buf_3_address0 = Y_buf_3_addr_reg_2727;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Y_buf_3_address0 = p_cast_fu_2138_p1;
    end else begin
        Y_buf_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Y_buf_3_ce0 = 1'b1;
    end else begin
        Y_buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            Y_buf_3_d0 = add_ln859_6_reg_2737;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            Y_buf_3_d0 = 16'd0;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Y_buf_3_d0 = lhs_fu_2160_p2;
        end else begin
            Y_buf_3_d0 = 'bx;
        end
    end else begin
        Y_buf_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1466_fu_2187_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln51_reg_2324_pp0_iter2_reg == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln51_reg_2324_pp0_iter1_reg == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (trunc_ln51_reg_2324_pp0_iter2_reg == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Y_buf_3_we0 = 1'b1;
    end else begin
        Y_buf_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_2283 == 1'd1) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten71_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten71_load = indvar_flatten71_fu_244;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load_3 = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load_3 = indvar_flatten_fu_232;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_kernel_load = 3'd0;
    end else begin
        ap_sig_allocacmp_kernel_load = kernel_fu_220;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_1460)) begin
            grp_load_fu_982_p1 = indvar_flatten_fu_232;
        end else if ((1'b1 == ap_condition_1455)) begin
            grp_load_fu_982_p1 = ap_sig_allocacmp_indvar_flatten_load_3;
        end else begin
            grp_load_fu_982_p1 = 'bx;
        end
    end else begin
        grp_load_fu_982_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign X_buf_0_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_10_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_11_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_12_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_13_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_14_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_15_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_16_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_17_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_18_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_19_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_1_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_20_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_21_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_22_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_23_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_24_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_25_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_26_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_27_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_28_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_29_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_2_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_30_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_31_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_32_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_33_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_34_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_35_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_36_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_37_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_38_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_39_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_3_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_40_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_41_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_42_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_43_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_44_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_4_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_5_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_6_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_7_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_8_address0 = zext_ln1317_fu_1153_p1;

assign X_buf_9_address0 = zext_ln1317_fu_1153_p1;

assign add_ln1319_1_fu_1212_p2 = (mul_ln1319_reg_2313 + 7'd15);

assign add_ln1319_2_fu_1222_p2 = (mul_ln1319_reg_2313 + 7'd16);

assign add_ln1319_3_fu_1243_p2 = (mul_ln1319_reg_2313 + 7'd17);

assign add_ln1319_4_fu_1909_p2 = (mul_ln1319_reg_2313 + 7'd18);

assign add_ln1319_5_fu_1253_p2 = (mul_ln1319_reg_2313 + 7'd19);

assign add_ln1319_6_fu_1263_p2 = (mul_ln1319_reg_2313 + 7'd20);

assign add_ln1319_fu_1202_p2 = (mul_ln1319_reg_2313 + 7'd14);

assign add_ln41_1_fu_1042_p2 = (ap_sig_allocacmp_indvar_flatten71_load + 11'd1);

assign add_ln41_2_fu_1137_p2 = (h_fu_236 + select_ln41_4_fu_1130_p3);

assign add_ln41_3_fu_1147_p2 = (zext_ln41_fu_1143_p1 + 8'd104);

assign add_ln41_fu_1999_p2 = (oh_fu_240 + 5'd1);

assign add_ln44_1_fu_1866_p2 = (grp_load_fu_982_p1 + 8'd1);

assign add_ln44_fu_2019_p2 = (select_ln41_fu_2005_p3 + 5'd1);

assign add_ln47_fu_1861_p2 = (select_ln44_reg_2308 + 3'd1);

assign add_ln859_1_fu_2155_p2 = (add_ln859_reg_2702 + trunc_ln864_3_fu_2146_p4);

assign add_ln859_2_fu_2080_p2 = (trunc_ln864_1_reg_2661 + trunc_ln864_2_reg_2666);

assign add_ln859_3_fu_2084_p2 = (trunc_ln3_reg_2656 + trunc_ln864_5_fu_2048_p4);

assign add_ln859_4_fu_2089_p2 = (add_ln859_3_fu_2084_p2 + add_ln859_2_fu_2080_p2);

assign add_ln859_6_fu_2179_p2 = ($signed(rhs_reg_2328_pp0_iter1_reg) + $signed(lhs_fu_2160_p2));

assign add_ln859_fu_2074_p2 = (trunc_ln864_4_fu_2039_p4 + factor_fu_2066_p3);

assign and_ln41_fu_1069_p2 = (xor_ln41_fu_1057_p2 & icmp_ln47_fu_1063_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1455 = ((1'b0 == ap_block_pp0_stage0) & (icmp_ln41_fu_1036_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_1460 = ((icmp_ln41_reg_2283 == 1'd0) & (1'b0 == ap_block_pp0_stage2) & (icmp_ln44_reg_2292 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign empty_66_fu_2123_p2 = (tmp_s_fu_2105_p3 + tmp_11_cast_fu_2119_p1);

assign empty_67_fu_2132_p2 = (empty_66_fu_2123_p2 + select_ln44_1_cast_fu_2129_p1);

assign factor_fu_2066_p3 = {{tmp_8_fu_2057_p4}, {1'd0}};

assign icmp_ln1466_fu_2187_p2 = ((sext_ln859_1_fu_2184_p1 == sub_ln1466_reg_2732) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_1036_p2 = ((ap_sig_allocacmp_indvar_flatten71_load == 11'd1840) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_1051_p2 = ((grp_load_fu_982_p1 == 8'd80) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_1063_p2 = ((ap_sig_allocacmp_kernel_load == 3'd4) ? 1'b1 : 1'b0);

assign indvars_iv_next295_fu_1232_p2 = (select_ln41_1_reg_2340 + 6'd2);

assign indvars_iv_next305_fu_1898_p2 = (h_load_reg_2334 + 6'd2);

assign lhs_fu_2160_p2 = (add_ln859_4_reg_2707 + add_ln859_1_fu_2155_p2);

assign mul_ln1319_fu_1093_p0 = mul_ln1319_fu_1093_p00;

assign mul_ln1319_fu_1093_p00 = select_ln44_fu_1081_p3;

assign mul_ln1319_fu_1093_p1 = 7'd21;

assign or_ln44_fu_1075_p2 = (icmp_ln44_fu_1051_p2 | and_ln41_fu_1069_p2);

assign p_cast_fu_2138_p1 = empty_67_fu_2132_p2;

assign select_ln41_1_fu_1123_p3 = ((icmp_ln44_reg_2292[0:0] == 1'b1) ? 6'd0 : w_fu_224);

assign select_ln41_2_fu_2012_p3 = ((icmp_ln44_reg_2292_pp0_iter1_reg[0:0] == 1'b1) ? add_ln41_fu_1999_p2 : oh_fu_240);

assign select_ln41_4_fu_1130_p3 = ((icmp_ln44_reg_2292[0:0] == 1'b1) ? 6'd8 : 6'd6);

assign select_ln41_5_fu_1903_p3 = ((icmp_ln44_reg_2292[0:0] == 1'b1) ? indvars_iv_next305_fu_1898_p2 : h_load_reg_2334);

assign select_ln41_fu_2005_p3 = ((icmp_ln44_reg_2292_pp0_iter1_reg[0:0] == 1'b1) ? 5'd0 : ow_fu_228);

assign select_ln44_1_cast_fu_2129_p1 = select_ln44_1_reg_2692;

assign select_ln44_1_fu_2025_p3 = ((and_ln41_reg_2302_pp0_iter1_reg[0:0] == 1'b1) ? add_ln44_fu_2019_p2 : select_ln41_fu_2005_p3);

assign select_ln44_2_fu_1237_p3 = ((and_ln41_reg_2302[0:0] == 1'b1) ? indvars_iv_next295_fu_1232_p2 : select_ln41_1_reg_2340);

assign select_ln44_3_fu_1872_p3 = ((icmp_ln44_reg_2292[0:0] == 1'b1) ? 8'd1 : add_ln44_1_fu_1866_p2);

assign select_ln44_fu_1081_p3 = ((or_ln44_fu_1075_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_kernel_load);

assign sext_ln859_1_fu_2184_p1 = rhs_reg_2328_pp0_iter2_reg;

assign sext_ln859_fu_2169_p1 = lhs_fu_2160_p2;

assign sub_ln1466_fu_2173_p2 = ($signed(17'd0) - $signed(sext_ln859_fu_2169_p1));

assign tmp_11_cast_fu_2119_p1 = tmp_7_fu_2112_p3;

assign tmp_7_fu_2112_p3 = {{select_ln41_2_reg_2686}, {2'd0}};

assign tmp_8_fu_2057_p4 = {{mul_ln1317_reg_2671[27:13]}};

assign tmp_s_fu_2105_p3 = {{select_ln41_2_reg_2686}, {4'd0}};

assign trunc_ln51_fu_1099_p1 = select_ln44_fu_1081_p3[1:0];

assign trunc_ln864_3_fu_2146_p4 = {{mul_ln864_3_reg_2697[28:13]}};

assign trunc_ln864_4_fu_2039_p4 = {{mul_ln864_4_reg_2676[28:13]}};

assign trunc_ln864_5_fu_2048_p4 = {{mul_ln864_5_reg_2681[28:13]}};

assign xor_ln41_fu_1057_p2 = (icmp_ln44_fu_1051_p2 ^ 1'd1);

assign zext_ln1317_fu_1153_p1 = add_ln41_3_fu_1147_p2;

assign zext_ln1319_1_fu_1207_p1 = add_ln1319_fu_1202_p2;

assign zext_ln1319_2_fu_1217_p1 = add_ln1319_1_fu_1212_p2;

assign zext_ln1319_3_fu_1227_p1 = add_ln1319_2_fu_1222_p2;

assign zext_ln1319_4_fu_1248_p1 = add_ln1319_3_fu_1243_p2;

assign zext_ln1319_5_fu_1914_p1 = add_ln1319_4_fu_1909_p2;

assign zext_ln1319_6_fu_1258_p1 = add_ln1319_5_fu_1253_p2;

assign zext_ln1319_7_fu_1268_p1 = add_ln1319_6_fu_1263_p2;

assign zext_ln41_fu_1143_p1 = add_ln41_2_fu_1137_p2;

endmodule //tiled_conv_conv_7x7
